server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_demo01?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: UserService

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka, http://localhost:9999/eureka